### ISSUE TITLE
Registros corridos, sem paginação

### ISSUE THREAD

**Issue by DePorto** [CMCuritiba/ramais#60]
**A sua melhoria está relacionada com um problema ? Por favor descreva.**
Na lista de ramais, tanto na apresentação quanto no admin, listar os registros corridos

**Descreva a solução que você gostaria**
Não trazer mais paginação de registros

**Descreva as alternativas que você considerou**
Manter como está, aparecem poucos registros, segundo avaliação inicial.

**Contexto adicional**
Visto que há a possibilidade de buscar registros digitando no campo de busca unificado do topo, pode-se retirar a paginação.
A paginação é para aliviar o carregamento da página?

**Comment by aleodoni** [comment]
@DePorto 
A paginação não interfere no desempenho; foi adicionada apenas como cosmética.
Simples de retirar.
