### ISSUE TITLE
Mesmo ramal em dois setores distintos

### ISSUE THREAD

**Issue by DePorto** [CMCuritiba/ramais#61]
**Descreva o bug**
Um mesmo número de ramal pode ser por engano cadastrado para setores diferentes

**Desktop (por favor preencha os campos abaixo):**
 - Chrome e Firefox

**Comment by aleodoni** [comment]
@DePorto 
Posso colocar um constraint para não deixar cadastrar o ramal 2X. Acho que é a melhor opção.

**Comment by aleodoni** [comment]
Adicionei a constraint unique = True no campo numero. Ficou assim : 
```
class Ramal(models.Model):
    
    numero = models.CharField(max_length=4, unique=True) # número do ramal
    tipo = models.CharField(max_length=1) # 0 - nenhum, 1 - geral, 2 - recepção, 3 - chefia
    visivel = models.BooleanField(default=True) # se o ramal aparece ou não na list
    setor_id = models.IntegerField() # referencia o setor do ramal

    class Meta:
        verbose_name_plural = "Ramais"
```

**Comment by aleodoni** [comment]
Preciso implementar no frontend agora uma chamada assíncrona para que ele valide o ramal digitado pelo usuário, verificando se o mesmo já foi cadastrado no sistema.
Para a inclusão ele apenas verifica se p número já foi cadastrado.
Para a alteração ele deve não só verificar apenas o número, mas o ID também e se for o mesmo validar a entrada, garantindo que o usuário está apenas alterando os dados do ramal. Se o ID for diferente, ele está tentando alterar o ramal para um número já cadastrado.

**Comment by aleodoni** [comment]
Foi implementado como descrito acima. Portanto na inclusão e alteração de ramais, o sistema verifica se o ramal já foi cadastrado. Se foi já emite mensagem de validação informando que o mesmo já foi cadastrado.
Para a alteração ele além de fazer a mesma verificação, também verifica se o ID do ramal também, não deixando alterar caso o ID seja diferente.
