### ISSUE TITLE
Retirar CAIXA ALTA na exibição de nomes

### ISSUE THREAD

**Issue by DePorto** [CMCuritiba/ramais#62]
O nome das pessoas aparece em caixa alta na lista de ramais

Sugere-se que apenas a letra inicial de cada nome apareça em letra maiúscula.

Manter como está não fica homogêneo com a exibição dos nomes de setores.

**Comment by aleodoni** [comment]
@DePorto 
Vou ter que formatar essa informação no momento de buscá-la pois a mesma já vem dessa maneira.
