### ISSUE TITLE
Problema botão impressora nas listas

### ISSUE THREAD

**Issue by DePorto** [CMCuritiba/ramais#65]
O botão imprimir nas listagens não funciona nas listas.

**Para Reproduzir**
Em qualquer lista, o botão de imprimir não funciona

**Comportamento Esperado**
No Chrome, não dá resposta nenhuma (talvez por conta do bloqueio de pop-up).
No Firefox Quantum (67.0.2), aparece o aviso de pop-up bloqueado, contudo depois de confirmar pop-ups para o endereço do sistema, a tela apenas pisca, e nada acontece (nem sinal do navegador de que uma tela tenha sido bloqueada)

**Desktop (por favor preencha os campos abaixo):**
 - Browser : no Chrome não há sinal, no FFQuantum, aparece o bloqueio e a tela pisca ao clicar no botão.

**Comment by aleodoni** [comment]
@DePorto 
Atualmente o relatório é gerado no backend. Na verdade é um blob (conteúdo binário) e depois o front se vira pra ajeitar as coisas para mostrar como pdf.
O ideal é fazer toda a geração no front, mas ainda estou estudando a melhor biblioteca para fazer isso.
Fiz algumas alterações no código para ver se esse problema por hora se resolve. Vou atualizar o staging para que você possa testar.
